ALTER TABLE invoices
ADD COLUMN customer_phone VARCHAR(255) NOT NULL DEFAULT '000000000';

ALTER TABLE invoices
ADD COLUMN employed_code CHAR(25) NOT NULL DEFAULT 'TEMP';



ALTER TABLE invoices
ALTER COLUMN customer_email VARCHAR(255) NOT NULL DEFAULT ''; 

ALTER TABLE products
ALTER COLUMN code VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE invoices
ALTER COLUMN employed_code VARCHAR(255) NOT NULL DEFAULT '';